// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB77k4vHn3Wv4DOVkVSzFTfwah-MYrEtC0',
    appId: '1:646657918031:web:033b089148bc42299b963a',
    messagingSenderId: '646657918031',
    projectId: 'apps-e6a2e',
    authDomain: 'apps-e6a2e.firebaseapp.com',
    storageBucket: 'apps-e6a2e.firebasestorage.app',
    measurementId: 'G-S2EBSGR0VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zi7Hw4JR43ejYkxcfBmxHUZvzf1ovO4',
    appId: '1:646657918031:android:9734859dbe8bfa0d9b963a',
    messagingSenderId: '646657918031',
    projectId: 'apps-e6a2e',
    storageBucket: 'apps-e6a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjtUB0ggQv8aHIhtNXv6EHo-2CPT8Tuvs',
    appId: '1:646657918031:ios:7354d86390505fbf9b963a',
    messagingSenderId: '646657918031',
    projectId: 'apps-e6a2e',
    storageBucket: 'apps-e6a2e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjtUB0ggQv8aHIhtNXv6EHo-2CPT8Tuvs',
    appId: '1:646657918031:ios:7354d86390505fbf9b963a',
    messagingSenderId: '646657918031',
    projectId: 'apps-e6a2e',
    storageBucket: 'apps-e6a2e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB77k4vHn3Wv4DOVkVSzFTfwah-MYrEtC0',
    appId: '1:646657918031:web:dc7ab94c1001d7929b963a',
    messagingSenderId: '646657918031',
    projectId: 'apps-e6a2e',
    authDomain: 'apps-e6a2e.firebaseapp.com',
    storageBucket: 'apps-e6a2e.firebasestorage.app',
    measurementId: 'G-SQ2HZLPH0C',
  );
}
